services:
  - type: web
    name: nats
    runtime: docker
    image:
      url: docker.io/library/nats:2.10-alpine
    plan: free
    startCommand: nats-server -js

  - type: web
    name: event-collector
    runtime: docker
    image:
      url: ghcr.io/rahul09123/event-collector:latest
    plan: free
    startCommand: /app/event-collector
    healthCheckPath: /healthz
    envVars:
      - key: NATS_URL
        value: nats://nats:4222
      - key: HTTP_ADDR
        value: :8080

  - type: web
    name: analyzer
    runtime: docker
    image:
      url: ghcr.io/rahul09123/analyzer:latest
    plan: free
    startCommand: /app/analyzer
    healthCheckPath: /healthz
    envVars:
      - key: NATS_URL
        value: nats://nats:4222
      - key: HTTP_ADDR
        value: :8081

  - type: web
    name: alert-manager
    runtime: docker
    image:
      url: ghcr.io/rahul09123/alert-manager:latest
    plan: free
    startCommand: /app/alert-manager
    healthCheckPath: /healthz
    envVars:
      - key: NATS_URL
        value: nats://nats:4222
      - key: HTTP_ADDR
        value: :8082

  - type: web
    name: prometheus
    runtime: docker
    image:
      url: docker.io/prom/prometheus:v2.54.1
    plan: free
    startCommand: prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
