apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krtms
resources:
  - namespace.yaml
  - nats.yaml
  - rbac-event-collector.yaml
  - event-collector.yaml
  - analyzer.yaml
  - alert-manager.yaml
