apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-collector-sa
  namespace: krtms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-collector-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-collector-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: event-collector-sa
    namespace: krtms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-collector-pod-reader
